export const INDUSTRIES = [
  "Life Insurance",
  "Health Insurance",
  "Medicare",
  "Property & Casualty",
  "Auto Insurance",
  "Home Insurance",
  "Commercial Insurance",
  "Financial Planning",
  "Mortgage & Lending",
  "Real Estate",
  "Tax Preparation",
  "Accounting & CPA",
  "Legal Services",
  "Wealth Management",
  "Retirement Planning",
  "Benefits Administration",
  "HR & Payroll",
  "Healthcare",
  "Dental & Vision",
  "Banking & Credit Union",
  "Investment Advisory",
  "Estate Planning",
  "Workers Compensation",
  "Surety & Bonds",
  "Other",
] as const;

export type Industry = (typeof INDUSTRIES)[number];
