import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ── helpers ───────────────────────────────────────────────────────────────────

type FieldDef = {
  label: string;
  fieldType: string;
  placeholder?: string;
  helpText?: string;
  required?: boolean;
  encrypted?: boolean;
  maskInput?: boolean;
  confirmField?: boolean;
  dropdownOptions?: string; // JSON string
};

function f(
  label: string,
  fieldType: string,
  opts: Partial<Omit<FieldDef, "label" | "fieldType">> = {}
): FieldDef {
  return { label, fieldType, ...opts };
}

function dd(options: string[]): string {
  return JSON.stringify(options);
}

// ── template definitions ──────────────────────────────────────────────────────

const TEMPLATES: Array<{
  id: string;
  title: string;
  description: string;
  category: string;
  industry: string;
  type: "SECURE_LINK" | "FORM";
  linkType?: string;
  optionsJson?: string;
  fields?: FieldDef[];
  tags: string;
  isFeatured: boolean;
  complianceGuarded: boolean;
  coreFieldLabels?: string[]; // labels of fields that are "locked" in guarded mode
}> = [
  // ── Original 10 (insurance / banking) ─────────────────────────────────────

  {
    id: "tpl-bank-account-collection",
    title: "Bank Account Collection",
    description: "Securely collect routing number, account number, and account type from a client.",
    category: "Banking",
    industry: "BANKING",
    type: "SECURE_LINK",
    linkType: "BANKING_INFO",
    optionsJson: JSON.stringify({ collectBothAccounts: false }),
    tags: "banking,routing,account",
    isFeatured: true,
    complianceGuarded: false,
  },
  {
    id: "tpl-ssn-tax-id-collection",
    title: "SSN / Tax ID Collection",
    description: "Collect a Social Security Number or Tax ID for applications and verifications.",
    category: "Compliance",
    industry: "GENERAL",
    type: "SECURE_LINK",
    linkType: "SSN_ONLY",
    tags: "ssn,tax,compliance,identity",
    isFeatured: false,
    complianceGuarded: false,
  },
  {
    id: "tpl-photo-id-verification",
    title: "Photo ID Verification",
    description: "Ask your client to upload a government-issued photo ID (driver's license or passport).",
    category: "Compliance",
    industry: "GENERAL",
    type: "SECURE_LINK",
    linkType: "ID_UPLOAD",
    optionsJson: JSON.stringify({ documentType: "DRIVERS_LICENSE" }),
    tags: "id,identity,kyc,compliance",
    isFeatured: true,
    complianceGuarded: false,
  },
  {
    id: "tpl-full-client-intake",
    title: "Full Client Intake",
    description: "Collect personal info, SSN, and banking details in a single secure link.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "SECURE_LINK",
    linkType: "FULL_INTAKE",
    tags: "intake,full,insurance,banking",
    isFeatured: true,
    complianceGuarded: false,
  },
  {
    id: "tpl-auto-insurance-quote",
    title: "Auto Insurance Quote",
    description: "Collect driver info, vehicle details, and contact info for an auto insurance quote.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    tags: "auto,vehicle,insurance,quote",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home Address", "address", { required: true }),
      f("Vehicle Year", "text", { placeholder: "e.g. 2021", required: true }),
      f("Vehicle Make & Model", "text", { placeholder: "e.g. Toyota Camry", required: true }),
      f("VIN Number", "text", { required: false, encrypted: true }),
      f("Current Insurance Provider", "text", { required: false }),
      f("Social Security Number", "ssn", { required: false, encrypted: true, maskInput: true, helpText: "Required for MVR check" }),
    ],
  },
  {
    id: "tpl-life-insurance-application",
    title: "Life Insurance Application",
    description: "Collect personal, health, and beneficiary information for a life insurance application.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    tags: "life,insurance,application,beneficiary",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Full Legal Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home Address", "address", { required: true }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Coverage Amount Requested", "dropdown", { required: true, dropdownOptions: dd(["$250,000","$500,000","$750,000","$1,000,000","$2,000,000+"]) }),
      f("Tobacco Use in Last 12 Months?", "dropdown", { required: true, dropdownOptions: dd(["No","Yes"]) }),
      f("Primary Beneficiary Name", "text", { required: true }),
      f("Beneficiary Relationship", "dropdown", { required: true, dropdownOptions: dd(["Spouse","Child","Parent","Sibling","Other"]) }),
    ],
  },
  {
    id: "tpl-health-insurance-enrollment",
    title: "Health Insurance Enrollment",
    description: "Gather personal details and coverage preferences for health insurance enrollment.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    tags: "health,insurance,enrollment,aca",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home Address", "address", { required: true }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Employer Name", "text", { required: false }),
      f("Household Size", "dropdown", { required: true, dropdownOptions: dd(["1","2","3","4","5","6+"]) }),
      f("Annual Household Income", "text", { placeholder: "e.g. $55,000", required: true, encrypted: true }),
      f("Preferred Coverage Type", "dropdown", { required: false, dropdownOptions: dd(["HMO","PPO","EPO","HDHP – HSA Compatible","No Preference"]) }),
    ],
  },
  {
    id: "tpl-mortgage-pre-qualification",
    title: "Mortgage Pre-Qualification",
    description: "Collect income, assets, and banking info needed to pre-qualify a mortgage applicant.",
    category: "Mortgage",
    industry: "MORTGAGE",
    type: "FORM",
    tags: "mortgage,loan,prequalification,banking",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Legal Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Current Address", "address", { required: true }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Gross Annual Income", "text", { placeholder: "e.g. $90,000", required: true, encrypted: true }),
      f("Employment Status", "dropdown", { required: true, dropdownOptions: dd(["Employed Full-Time","Employed Part-Time","Self-Employed","Retired","Other"]) }),
      f("Bank Routing Number", "routing", { required: true, encrypted: true, maskInput: true }),
      f("Bank Account Number", "bank_account", { required: true, encrypted: true, maskInput: true, confirmField: true }),
    ],
  },
  {
    id: "tpl-medicare-supplement-enrollment",
    title: "Medicare Supplement Enrollment",
    description: "Collect Medicare details, personal info, and current coverage for supplement enrollment.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    tags: "medicare,supplement,enrollment,senior",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Full Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home Address", "address", { required: true }),
      f("Medicare Beneficiary Identifier (MBI)", "text", { required: true, encrypted: true, maskInput: true, helpText: "Found on your red, white, and blue Medicare card" }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Part A Effective Date", "date", { required: false }),
      f("Part B Effective Date", "date", { required: false }),
      f("Desired Supplement Plan", "dropdown", { required: false, dropdownOptions: dd(["Plan G","Plan N","Plan F","Plan K","Plan L","Not Sure"]) }),
    ],
  },
  {
    id: "tpl-business-banking-setup",
    title: "Business Banking Setup",
    description: "Collect business entity info, EIN, and banking details for a new business account.",
    category: "Banking",
    industry: "BANKING",
    type: "FORM",
    tags: "business,banking,ein,account",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Business Legal Name", "text", { required: true }),
      f("DBA / Trade Name", "text", { required: false }),
      f("Employer Identification Number (EIN)", "text", { required: true, encrypted: true, maskInput: true }),
      f("Business Type", "dropdown", { required: true, dropdownOptions: dd(["Sole Proprietorship","LLC","S-Corp","C-Corp","Partnership","Non-Profit"]) }),
      f("Business Address", "address", { required: true }),
      f("Owner Full Name", "text", { required: true }),
      f("Owner Date of Birth", "date", { required: true }),
      f("Owner Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Bank Routing Number", "routing", { required: true, encrypted: true, maskInput: true }),
      f("Bank Account Number", "bank_account", { required: true, encrypted: true, maskInput: true, confirmField: true }),
    ],
  },

  // ── HR & Compliance (new 10) ───────────────────────────────────────────────

  {
    id: "tpl-w9-contractor-tax-intake",
    title: "W-9 Contractor Tax Intake",
    description: "IRS-aligned intake to collect taxpayer name, classification, address, TIN, and certification. Use as a precursor to issuing a 1099.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "w9,contractor,tax,irs,tin,1099",
    isFeatured: true,
    complianceGuarded: true,
    coreFieldLabels: ["Legal Name", "Federal Tax Classification", "Address", "TIN Type", "Taxpayer ID Number", "FATCA / Backup Withholding Certification", "Signature", "Date"],
    fields: [
      f("Legal Name", "text", { required: true, helpText: "Name as shown on your income tax return" }),
      f("Business / Disregarded Entity Name", "text", { required: false, helpText: "If different from above — leave blank if same" }),
      f("Federal Tax Classification", "dropdown", { required: true, dropdownOptions: dd(["Individual / Sole Proprietor","C Corporation","S Corporation","Partnership","Trust / Estate","LLC – Single Member (Disregarded)","LLC – C Corp Election","LLC – S Corp Election","LLC – Partnership Election","Other"]) }),
      f("Exempt Payee Code (if any)", "text", { required: false, helpText: "Leave blank if not applicable" }),
      f("FATCA Exemption Code (if any)", "text", { required: false, helpText: "Leave blank if not applicable" }),
      f("Address", "address", { required: true }),
      f("TIN Type", "dropdown", { required: true, dropdownOptions: dd(["Social Security Number (SSN)","Employer Identification Number (EIN)"]) }),
      f("Taxpayer ID Number", "ssn", { required: true, encrypted: true, maskInput: true, helpText: "SSN or EIN — encrypted and stored securely" }),
      f("FATCA / Backup Withholding Certification", "dropdown", { required: true, dropdownOptions: dd(["I certify that the TIN provided is correct, I am not subject to backup withholding, and I am a U.S. person"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-w4-employee-withholding-intake",
    title: "W-4 Employee Withholding Intake",
    description: "IRS-aligned intake for employee federal withholding elections. Employer transfers into official W-4 on file.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "w4,employee,withholding,irs,payroll,tax",
    isFeatured: true,
    complianceGuarded: true,
    coreFieldLabels: ["Filing Status", "Signature", "Date"],
    fields: [
      f("Full Legal Name", "text", { required: true }),
      f("SSN (last 4 for verification)", "text", { required: false, encrypted: true, maskInput: true, helpText: "Optional — for employer records only" }),
      f("Filing Status", "dropdown", { required: true, dropdownOptions: dd(["Single or Married Filing Separately","Married Filing Jointly (or Qualifying Surviving Spouse)","Head of Household"]) }),
      f("Multiple Jobs or Spouse Also Works?", "dropdown", { required: true, dropdownOptions: dd(["Yes","No"]) }),
      f("Claim Dependents — Total Amount", "text", { required: false, encrypted: true, placeholder: "e.g. $2,000", helpText: "From Step 3 of IRS W-4 worksheet" }),
      f("Other Income Not From Jobs (annual)", "text", { required: false, encrypted: true, placeholder: "e.g. $3,000" }),
      f("Deductions (if itemizing)", "text", { required: false, encrypted: true, placeholder: "e.g. $14,000" }),
      f("Additional Withholding Per Pay Period", "text", { required: false, encrypted: true, placeholder: "e.g. $50" }),
      f("Exempt From Withholding?", "dropdown", { required: true, dropdownOptions: dd(["No — withhold per elections above","Yes — I meet both IRS exemption conditions"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-i9-section1-work-authorization",
    title: "I-9 Section 1 — Work Authorization Intake",
    description: "USCIS-aligned Section 1 intake. Employee self-attests identity and work authorization. Note: employer must still complete Section 2 with document verification.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "i9,uscis,i-9,immigration,work,authorization,employment,eligibility",
    isFeatured: true,
    complianceGuarded: true,
    coreFieldLabels: ["Last Name", "First Name", "Date of Birth", "Citizenship / Immigration Status", "Employee Attestation", "Signature", "Date"],
    fields: [
      f("Last Name (Family Name)", "text", { required: true }),
      f("First Name (Given Name)", "text", { required: true }),
      f("Middle Initial", "text", { required: false }),
      f("Other Last Names Used (maiden, etc.)", "text", { required: false }),
      f("Current Address", "address", { required: true }),
      f("Date of Birth", "date", { required: true, encrypted: true }),
      f("U.S. Social Security Number", "ssn", { required: false, encrypted: true, maskInput: true, helpText: "Required only if your employer participates in E-Verify" }),
      f("Email Address", "email", { required: false }),
      f("Phone Number", "phone", { required: false }),
      f("Citizenship / Immigration Status", "dropdown", { required: true, dropdownOptions: dd(["A citizen of the United States","A noncitizen national of the United States","A lawful permanent resident","An alien authorized to work until the date below"]) }),
      f("Alien Registration / USCIS Number (if applicable)", "text", { required: false, encrypted: true, helpText: "A-Number or USCIS Number — starts with A" }),
      f("Form I-94 Admission Number (if applicable)", "text", { required: false, encrypted: true }),
      f("Foreign Passport Number (if applicable)", "text", { required: false, encrypted: true }),
      f("Country of Issuance (if applicable)", "text", { required: false }),
      f("Work Authorization Expiration Date (if applicable)", "date", { required: false }),
      f("Document List Note", "text", { required: false, helpText: "List A (e.g. Passport) OR List B + List C (e.g. Driver License + SSN Card). Your employer will complete Section 2 after reviewing originals." }),
      f("Employee Attestation", "dropdown", { required: true, dropdownOptions: dd(["I attest, under penalty of perjury, that I am aware that federal law provides for imprisonment and/or fines for false statements or use of false documents in connection with the completion of this form"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-direct-deposit-authorization",
    title: "Direct Deposit Authorization",
    description: "Collect employee or contractor banking info to set up direct deposit with a signed authorization.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "direct deposit,payroll,banking,ach,routing,employee",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Employee / Contractor Name", "text", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Bank Name", "text", { required: true }),
      f("Bank Routing Number", "routing", { required: true, encrypted: true, maskInput: true }),
      f("Bank Account Number", "bank_account", { required: true, encrypted: true, maskInput: true, confirmField: true }),
      f("Account Type", "dropdown", { required: true, dropdownOptions: dd(["Checking","Savings"]) }),
      f("Deposit Amount", "dropdown", { required: true, dropdownOptions: dd(["100% of net pay","Partial amount (specify in notes)","Split between accounts (specify in notes)"]) }),
      f("Notes / Special Instructions", "text", { required: false }),
      f("Authorization", "dropdown", { required: true, dropdownOptions: dd(["I authorize the above-named company to initiate credit entries to my account and to reverse any erroneous entries"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-independent-contractor-onboarding",
    title: "Independent Contractor Onboarding",
    description: "Full onboarding intake for new contractors — identity, contact, service type, tax profile, and payment method.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "contractor,onboarding,1099,freelance,independent",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Legal Name", "text", { required: true }),
      f("Business / DBA Name", "text", { required: false }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Business Address", "address", { required: true }),
      f("Service / Work Description", "text", { required: true, placeholder: "e.g. Software development, bookkeeping, design" }),
      f("Federal Tax Classification", "dropdown", { required: true, dropdownOptions: dd(["Sole Proprietor / Individual","Single-Member LLC","Partnership / Multi-Member LLC","S Corporation","C Corporation"]) }),
      f("SSN or EIN", "ssn", { required: true, encrypted: true, maskInput: true, helpText: "Used for 1099 reporting" }),
      f("Payment Method Preference", "dropdown", { required: true, dropdownOptions: dd(["Direct Deposit (ACH)","Check","Wire Transfer","Other"]) }),
      f("Anticipated Start Date", "date", { required: false }),
      f("Acknowledgment", "dropdown", { required: true, dropdownOptions: dd(["I confirm that all information provided is accurate and I understand I am engaged as an independent contractor, not an employee"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-employee-emergency-contact",
    title: "Employee Emergency Contact & Medical Notes",
    description: "Collect primary and secondary emergency contacts, relationship, and optional medical/allergy notes with signed consent.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "emergency contact,employee,medical,allergy,hr",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Employee Full Name", "text", { required: true }),
      f("Employee Email", "email", { required: false }),
      f("Primary Emergency Contact Name", "text", { required: true }),
      f("Primary Contact Relationship", "dropdown", { required: true, dropdownOptions: dd(["Spouse / Partner","Parent","Sibling","Child","Friend","Other"]) }),
      f("Primary Contact Phone", "phone", { required: true }),
      f("Primary Contact Email", "email", { required: false }),
      f("Secondary Emergency Contact Name", "text", { required: false }),
      f("Secondary Contact Relationship", "dropdown", { required: false, dropdownOptions: dd(["Spouse / Partner","Parent","Sibling","Child","Friend","Other"]) }),
      f("Secondary Contact Phone", "phone", { required: false }),
      f("Secondary Contact Email", "email", { required: false }),
      f("Known Medical Conditions / Allergies", "text", { required: false, encrypted: true, helpText: "e.g. Penicillin allergy, diabetes, EpiPen required" }),
      f("Current Medications", "text", { required: false, encrypted: true }),
      f("Special Instructions for Emergency Responders", "text", { required: false, encrypted: true }),
      f("Consent", "dropdown", { required: true, dropdownOptions: dd(["I consent to this information being securely stored and shared with emergency responders if necessary"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-background-check-consent-fcra",
    title: "Background Check Consent (FCRA)",
    description: "FCRA-compliant disclosure and authorization for consumer background reports. Includes standalone disclosure, written authorization, and rights acknowledgment.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "background check,fcra,consent,authorization,screening,hr",
    isFeatured: false,
    complianceGuarded: true,
    coreFieldLabels: ["Applicant Full Name", "Date of Birth", "Social Security Number", "FCRA Disclosure Acknowledgment", "Written Authorization", "Applicant Rights Acknowledgment", "Signature", "Date"],
    fields: [
      f("Applicant Full Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true, encrypted: true }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Current Address", "address", { required: true }),
      f("Previous Address (if less than 2 years at current)", "text", { required: false }),
      f("Driver's License Number and State (if applicable)", "text", { required: false, encrypted: true }),
      f("FCRA Disclosure Acknowledgment", "dropdown", { required: true, dropdownOptions: dd(["I have received, read, and understand the standalone written disclosure that a consumer report may be obtained for employment purposes"]) }),
      f("Written Authorization", "dropdown", { required: true, dropdownOptions: dd(["I authorize the company and its designated consumer reporting agency to obtain a consumer report and/or investigative consumer report about me"]) }),
      f("Applicant Rights Acknowledgment", "dropdown", { required: true, dropdownOptions: dd(["I acknowledge receipt of 'A Summary of Your Rights Under the Fair Credit Reporting Act'"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-nda-acknowledgment-esign",
    title: "NDA Acknowledgment & E-Sign",
    description: "Capture party details, effective date, and a binding e-signature acknowledging receipt and agreement to the terms of a non-disclosure agreement.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "nda,non-disclosure,confidentiality,agreement,esign",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Legal Name", "text", { required: true }),
      f("Title / Role", "text", { required: false }),
      f("Company / Organization", "text", { required: false }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: false }),
      f("Effective Date of Agreement", "date", { required: true }),
      f("NDA Summary Acknowledgment", "dropdown", { required: true, dropdownOptions: dd(["I have read and understand the Non-Disclosure Agreement presented to me"]) }),
      f("Agreement to Terms", "dropdown", { required: true, dropdownOptions: dd(["I agree to be legally bound by the terms of this Non-Disclosure Agreement"]) }),
      f("Confidential Information Description (optional)", "text", { required: false, helpText: "Briefly describe the nature of information covered, if applicable" }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-offer-letter-acceptance",
    title: "Offer Letter Acceptance",
    description: "Candidate confirms position, start date, and compensation details, then accepts or declines with a binding e-signature.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "offer letter,hiring,acceptance,onboarding,hr,candidate",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Candidate Full Name", "text", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: false }),
      f("Position / Job Title", "text", { required: true }),
      f("Department / Team", "text", { required: false }),
      f("Proposed Start Date", "date", { required: true }),
      f("Employment Type", "dropdown", { required: true, dropdownOptions: dd(["Full-Time","Part-Time","Contract","Temporary","Internship"]) }),
      f("Compensation Summary", "text", { required: false, encrypted: true, placeholder: "e.g. $85,000/yr base + benefits", helpText: "Encrypted — only you can view" }),
      f("Decision", "dropdown", { required: true, dropdownOptions: dd(["I accept this offer and agree to the terms outlined","I decline this offer"]) }),
      f("Questions or Comments", "text", { required: false }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-general-new-client-secure-intake",
    title: "General New Client Secure Intake",
    description: "Flexible all-purpose intake — identity, contact, address, optional SSN/TIN, optional banking, file upload notes, and signed consent.",
    category: "General",
    industry: "GENERAL",
    type: "FORM",
    tags: "intake,general,client,onboarding,identity",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Name", "text", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home / Business Address", "address", { required: true }),
      f("Date of Birth", "date", { required: false, encrypted: true }),
      f("Social Security Number or TIN", "ssn", { required: false, encrypted: true, maskInput: true, helpText: "Optional — only provide if requested by your agent" }),
      f("Bank Routing Number", "routing", { required: false, encrypted: true, maskInput: true }),
      f("Bank Account Number", "bank_account", { required: false, encrypted: true, maskInput: true, confirmField: true }),
      f("Document Upload Notes", "text", { required: false, helpText: "List any documents you intend to provide separately (e.g. photo ID, proof of income)" }),
      f("Consent", "dropdown", { required: true, dropdownOptions: dd(["I authorize submission of the above information and confirm it is accurate to the best of my knowledge"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
];

// ── seed ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Seeding system templates...");

  for (const t of TEMPLATES) {
    const fieldsJson = t.fields ? JSON.stringify(t.fields) : null;
    const coreFieldLabels = t.coreFieldLabels ? JSON.stringify(t.coreFieldLabels) : null;

    await prisma.systemTemplate.upsert({
      where: { id: t.id },
      update: {
        title: t.title,
        description: t.description,
        category: t.category,
        industry: t.industry,
        type: t.type,
        linkType: t.linkType ?? null,
        optionsJson: t.optionsJson ?? null,
        fieldsJson,
        tags: t.tags,
        isFeatured: t.isFeatured,
        complianceGuarded: t.complianceGuarded,
        coreFieldLabels,
        isActive: true,
      },
      create: {
        id: t.id,
        title: t.title,
        description: t.description,
        category: t.category,
        industry: t.industry,
        type: t.type,
        linkType: t.linkType ?? null,
        optionsJson: t.optionsJson ?? null,
        fieldsJson,
        tags: t.tags,
        isFeatured: t.isFeatured,
        complianceGuarded: t.complianceGuarded,
        coreFieldLabels,
        isActive: true,
      },
    });
    console.log(`  ✓ ${t.title}`);
  }

  console.log(`\nSeeded ${TEMPLATES.length} system templates.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
