import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const TEMPLATES = [
  // ── Secure Link Templates ────────────────────────────────────────────────
  {
    title: "Bank Account Collection",
    description: "Securely collect routing number, account number, and account type from a client.",
    category: "Banking",
    industry: "BANKING",
    type: "SECURE_LINK",
    linkType: "BANKING_INFO",
    optionsJson: JSON.stringify({ collectBothAccounts: false }),
    tags: "banking,routing,account",
    isFeatured: true,
  },
  {
    title: "SSN / Tax ID Collection",
    description: "Collect a Social Security Number or Tax ID for applications and verifications.",
    category: "Compliance",
    industry: "GENERAL",
    type: "SECURE_LINK",
    linkType: "SSN_ONLY",
    optionsJson: null,
    tags: "ssn,tax,compliance,identity",
    isFeatured: false,
  },
  {
    title: "Photo ID Verification",
    description: "Ask your client to upload a government-issued photo ID (driver's license or passport).",
    category: "Compliance",
    industry: "GENERAL",
    type: "SECURE_LINK",
    linkType: "ID_UPLOAD",
    optionsJson: JSON.stringify({ documentType: "DRIVERS_LICENSE" }),
    tags: "id,identity,kyc,compliance",
    isFeatured: true,
  },
  {
    title: "Full Client Intake",
    description: "Collect personal info, SSN, and banking details in a single secure link.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "SECURE_LINK",
    linkType: "FULL_INTAKE",
    optionsJson: null,
    tags: "intake,full,insurance,banking",
    isFeatured: true,
  },

  // ── Form Templates ───────────────────────────────────────────────────────
  {
    title: "Auto Insurance Quote",
    description: "Collect driver info, vehicle details, and contact info for an auto insurance quote.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    linkType: null,
    optionsJson: null,
    tags: "auto,vehicle,insurance,quote",
    isFeatured: true,
    fieldsJson: JSON.stringify([
      { label: "Full Name", fieldType: "text", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Date of Birth", fieldType: "date", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Email Address", fieldType: "email", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Phone Number", fieldType: "phone", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Home Address", fieldType: "address", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Vehicle Year", fieldType: "text", placeholder: "e.g. 2021", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Vehicle Make & Model", fieldType: "text", placeholder: "e.g. Toyota Camry", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "VIN Number", fieldType: "text", required: false, encrypted: true, maskInput: false, confirmField: false },
      { label: "Current Insurance Provider", fieldType: "text", required: false, encrypted: false, maskInput: false, confirmField: false },
      { label: "Social Security Number", fieldType: "ssn", required: false, encrypted: true, maskInput: true, confirmField: false, helpText: "Required for MVR check" },
    ]),
  },
  {
    title: "Life Insurance Application",
    description: "Collect personal, health, and beneficiary information for a life insurance application.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    linkType: null,
    optionsJson: null,
    tags: "life,insurance,application,beneficiary",
    isFeatured: false,
    fieldsJson: JSON.stringify([
      { label: "Full Legal Name", fieldType: "text", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Date of Birth", fieldType: "date", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Email Address", fieldType: "email", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Phone Number", fieldType: "phone", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Home Address", fieldType: "address", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Social Security Number", fieldType: "ssn", required: true, encrypted: true, maskInput: true, confirmField: false },
      { label: "Coverage Amount Requested", fieldType: "dropdown", required: true, encrypted: false, maskInput: false, confirmField: false, dropdownOptions: JSON.stringify(["$250,000","$500,000","$750,000","$1,000,000","$2,000,000+"]) },
      { label: "Tobacco Use in Last 12 Months?", fieldType: "dropdown", required: true, encrypted: false, maskInput: false, confirmField: false, dropdownOptions: JSON.stringify(["No","Yes"]) },
      { label: "Primary Beneficiary Name", fieldType: "text", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Beneficiary Relationship", fieldType: "dropdown", required: true, encrypted: false, maskInput: false, confirmField: false, dropdownOptions: JSON.stringify(["Spouse","Child","Parent","Sibling","Other"]) },
    ]),
  },
  {
    title: "Health Insurance Enrollment",
    description: "Gather personal details and coverage preferences for health insurance enrollment.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    linkType: null,
    optionsJson: null,
    tags: "health,insurance,enrollment,aca",
    isFeatured: true,
    fieldsJson: JSON.stringify([
      { label: "Full Name", fieldType: "text", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Date of Birth", fieldType: "date", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Email Address", fieldType: "email", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Phone Number", fieldType: "phone", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Home Address", fieldType: "address", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Social Security Number", fieldType: "ssn", required: true, encrypted: true, maskInput: true, confirmField: false },
      { label: "Employer Name", fieldType: "text", required: false, encrypted: false, maskInput: false, confirmField: false },
      { label: "Household Size", fieldType: "dropdown", required: true, encrypted: false, maskInput: false, confirmField: false, dropdownOptions: JSON.stringify(["1","2","3","4","5","6+"])},
      { label: "Annual Household Income", fieldType: "text", placeholder: "e.g. $55,000", required: true, encrypted: true, maskInput: false, confirmField: false },
      { label: "Preferred Coverage Type", fieldType: "dropdown", required: false, encrypted: false, maskInput: false, confirmField: false, dropdownOptions: JSON.stringify(["HMO","PPO","EPO","HDHP – HSA Compatible","No Preference"]) },
    ]),
  },
  {
    title: "Mortgage Pre-Qualification",
    description: "Collect income, assets, and banking info needed to pre-qualify a mortgage applicant.",
    category: "Mortgage",
    industry: "MORTGAGE",
    type: "FORM",
    linkType: null,
    optionsJson: null,
    tags: "mortgage,loan,prequalification,banking",
    isFeatured: true,
    fieldsJson: JSON.stringify([
      { label: "Full Legal Name", fieldType: "text", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Date of Birth", fieldType: "date", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Email Address", fieldType: "email", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Phone Number", fieldType: "phone", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Current Address", fieldType: "address", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Social Security Number", fieldType: "ssn", required: true, encrypted: true, maskInput: true, confirmField: false },
      { label: "Gross Annual Income", fieldType: "text", placeholder: "e.g. $90,000", required: true, encrypted: true, maskInput: false, confirmField: false },
      { label: "Employment Status", fieldType: "dropdown", required: true, encrypted: false, maskInput: false, confirmField: false, dropdownOptions: JSON.stringify(["Employed Full-Time","Employed Part-Time","Self-Employed","Retired","Other"]) },
      { label: "Bank Routing Number", fieldType: "routing", required: true, encrypted: true, maskInput: true, confirmField: false },
      { label: "Bank Account Number", fieldType: "bank_account", required: true, encrypted: true, maskInput: true, confirmField: true },
    ]),
  },
  {
    title: "Medicare Supplement Enrollment",
    description: "Collect Medicare details, personal info, and current coverage for supplement enrollment.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    linkType: null,
    optionsJson: null,
    tags: "medicare,supplement,enrollment,senior",
    isFeatured: false,
    fieldsJson: JSON.stringify([
      { label: "Full Name", fieldType: "text", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Date of Birth", fieldType: "date", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Email Address", fieldType: "email", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Phone Number", fieldType: "phone", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Home Address", fieldType: "address", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Medicare Beneficiary Identifier (MBI)", fieldType: "text", required: true, encrypted: true, maskInput: true, confirmField: false, helpText: "Found on your red, white, and blue Medicare card" },
      { label: "Social Security Number", fieldType: "ssn", required: true, encrypted: true, maskInput: true, confirmField: false },
      { label: "Part A Effective Date", fieldType: "date", required: false, encrypted: false, maskInput: false, confirmField: false },
      { label: "Part B Effective Date", fieldType: "date", required: false, encrypted: false, maskInput: false, confirmField: false },
      { label: "Desired Supplement Plan", fieldType: "dropdown", required: false, encrypted: false, maskInput: false, confirmField: false, dropdownOptions: JSON.stringify(["Plan G","Plan N","Plan F","Plan K","Plan L","Not Sure"]) },
    ]),
  },
  {
    title: "Business Banking Setup",
    description: "Collect business entity info, EIN, and banking details for a new business account.",
    category: "Banking",
    industry: "BANKING",
    type: "FORM",
    linkType: null,
    optionsJson: null,
    tags: "business,banking,ein,account",
    isFeatured: false,
    fieldsJson: JSON.stringify([
      { label: "Business Legal Name", fieldType: "text", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "DBA / Trade Name", fieldType: "text", required: false, encrypted: false, maskInput: false, confirmField: false },
      { label: "Employer Identification Number (EIN)", fieldType: "text", required: true, encrypted: true, maskInput: true, confirmField: false },
      { label: "Business Type", fieldType: "dropdown", required: true, encrypted: false, maskInput: false, confirmField: false, dropdownOptions: JSON.stringify(["Sole Proprietorship","LLC","S-Corp","C-Corp","Partnership","Non-Profit"]) },
      { label: "Business Address", fieldType: "address", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Owner Full Name", fieldType: "text", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Owner Date of Birth", fieldType: "date", required: true, encrypted: false, maskInput: false, confirmField: false },
      { label: "Owner Social Security Number", fieldType: "ssn", required: true, encrypted: true, maskInput: true, confirmField: false },
      { label: "Bank Routing Number", fieldType: "routing", required: true, encrypted: true, maskInput: true, confirmField: false },
      { label: "Bank Account Number", fieldType: "bank_account", required: true, encrypted: true, maskInput: true, confirmField: true },
    ]),
  },
];

async function main() {
  console.log("Seeding system templates...");

  for (const t of TEMPLATES) {
    await prisma.systemTemplate.upsert({
      where: { id: `tpl-${t.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}` },
      update: {
        title: t.title,
        description: t.description,
        category: t.category,
        industry: t.industry ?? null,
        type: t.type,
        linkType: t.linkType ?? null,
        optionsJson: t.optionsJson ?? null,
        fieldsJson: "fieldsJson" in t ? t.fieldsJson ?? null : null,
        tags: t.tags ?? null,
        isFeatured: t.isFeatured ?? false,
        isActive: true,
      },
      create: {
        id: `tpl-${t.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
        title: t.title,
        description: t.description,
        category: t.category,
        industry: t.industry ?? null,
        type: t.type,
        linkType: t.linkType ?? null,
        optionsJson: t.optionsJson ?? null,
        fieldsJson: "fieldsJson" in t ? t.fieldsJson ?? null : null,
        tags: t.tags ?? null,
        isFeatured: t.isFeatured ?? false,
        isActive: true,
      },
    });
    console.log(`  ✓ ${t.title}`);
  }

  console.log(`Seeded ${TEMPLATES.length} system templates.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
