import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ── helpers ───────────────────────────────────────────────────────────────────

type FieldDef = {
  label: string;
  fieldType: string;
  placeholder?: string;
  helpText?: string;
  required?: boolean;
  encrypted?: boolean;
  maskInput?: boolean;
  confirmField?: boolean;
  dropdownOptions?: string; // JSON string
};

function f(
  label: string,
  fieldType: string,
  opts: Partial<Omit<FieldDef, "label" | "fieldType">> = {}
): FieldDef {
  return { label, fieldType, ...opts };
}

function dd(options: string[]): string {
  return JSON.stringify(options);
}

function docSchema(title: string, body: string[]): string {
  return JSON.stringify({
    title,
    locale: "en-US",
    versionLabel: "v1",
    roles: ["PARTY_A", "PARTY_B"],
    variables: [
      { key: "effective_date", label: "Effective Date", type: "date_text", required: true, editable: true },
      { key: "party_a_name", label: "Party A Legal Name", type: "text", required: true, editable: true },
      { key: "party_a_address", label: "Party A Address", type: "address", required: true, editable: true },
      { key: "party_a_title", label: "Party A Title", type: "text", required: false, editable: true },
      { key: "party_a_email", label: "Party A Email", type: "email", required: false, editable: true },
      { key: "party_a_phone", label: "Party A Phone", type: "phone", required: false, editable: true },
      { key: "party_b_name", label: "Party B Legal Name", type: "text", required: true, editable: true },
      { key: "party_b_address", label: "Party B Address", type: "address", required: true, editable: true },
      { key: "party_b_title", label: "Party B Title", type: "text", required: false, editable: true },
      { key: "party_b_email", label: "Party B Email", type: "email", required: false, editable: true },
      { key: "party_b_phone", label: "Party B Phone", type: "phone", required: false, editable: true },
      { key: "consideration", label: "Consideration / Amount", type: "currency_usd", required: false, editable: true },
      { key: "term_start_date", label: "Term Start Date", type: "date_text", required: false, editable: true },
      { key: "term_end_date", label: "Term End Date", type: "date_text", required: false, editable: true },
      { key: "governing_law_state", label: "Governing Law (State)", type: "text", required: true, editable: true },
      { key: "custom_terms", label: "Additional Terms", type: "multiline", required: false, editable: true, maxLength: 3000 },
    ],
    clauses: [
      { id: "confidentiality", label: "Confidentiality", required: false, defaultEnabled: false },
      { id: "indemnity", label: "Indemnification", required: false, defaultEnabled: false },
      { id: "termination", label: "Termination Rights", required: false, defaultEnabled: true },
      { id: "governing_law", label: "Governing Law", required: true, defaultEnabled: true },
      { id: "additional_terms", label: "Additional Terms", required: false, defaultEnabled: true },
    ],
    blocks: [
      { id: "h1", kind: "heading", text: title },
      {
        id: "preamble",
        kind: "paragraph",
        editable: true,
        text: "This agreement is entered into as of {{effective_date}} by and between {{party_a_name}}, located at {{party_a_address}}, and {{party_b_name}}, located at {{party_b_address}}.",
      },
      {
        id: "purpose",
        kind: "paragraph",
        editable: true,
        text: "Purpose. The parties agree to the following business arrangement and obligations as set forth in this agreement.",
      },
      ...body.map((text, index) => ({
        id: `section_${index + 1}`,
        kind: "paragraph",
        editable: true,
        text,
      })),
      {
        id: "term",
        kind: "paragraph",
        editable: true,
        text: "Term. Unless terminated earlier in accordance with this agreement, the term begins on {{term_start_date}} and continues through {{term_end_date}}.",
      },
      {
        id: "consideration",
        kind: "paragraph",
        editable: true,
        text: "Compensation / Consideration. Any fees or consideration due under this agreement shall be {{consideration}} unless otherwise agreed in writing.",
      },
      {
        id: "confidentiality",
        kind: "paragraph",
        clauseId: "confidentiality",
        editable: true,
        text: "Confidentiality. Each party shall protect confidential information received from the other party and use such information only as permitted by this agreement.",
      },
      {
        id: "indemnity",
        kind: "paragraph",
        clauseId: "indemnity",
        editable: true,
        text: "Indemnification. Each party agrees to indemnify and hold harmless the other party from claims arising from its own breach, negligence, or willful misconduct.",
      },
      {
        id: "termination",
        kind: "paragraph",
        clauseId: "termination",
        editable: true,
        text: "Termination. Either party may terminate this agreement upon written notice if the other party materially breaches and fails to cure within a reasonable period.",
      },
      {
        id: "governing_law",
        kind: "paragraph",
        clauseId: "governing_law",
        editable: true,
        text: "Governing Law. This agreement shall be governed by and construed in accordance with the laws of {{governing_law_state}}, without regard to conflict-of-law principles.",
      },
      {
        id: "additional_terms",
        kind: "paragraph",
        clauseId: "additional_terms",
        editable: true,
        text: "Additional Terms. {{custom_terms}}",
      },
      { kind: "spacer", size: 18 },
      { id: "signature_heading", kind: "paragraph", text: "IN WITNESS WHEREOF, the parties have executed this agreement.", editable: true },
      { id: "party_a_sign", kind: "paragraph", text: "Party A: {{party_a_name}}  Title: {{party_a_title}}  Email: {{party_a_email}}  Phone: {{party_a_phone}}" },
      { id: "party_b_sign", kind: "paragraph", text: "Party B: {{party_b_name}}  Title: {{party_b_title}}  Email: {{party_b_email}}  Phone: {{party_b_phone}}" },
    ],
  });
}

function docSigningDefaults(): string {
  return JSON.stringify([
    { type: "FULL_NAME", role: "PARTY_A", page: 1, x: 0.1, y: 0.84, width: 0.2, height: 0.04, required: true },
    { type: "SIGNATURE", role: "PARTY_A", page: 1, x: 0.32, y: 0.84, width: 0.22, height: 0.05, required: true },
    { type: "DATE_SIGNED", role: "PARTY_A", page: 1, x: 0.56, y: 0.84, width: 0.16, height: 0.04, required: true },
    { type: "FULL_NAME", role: "PARTY_B", page: 1, x: 0.1, y: 0.91, width: 0.2, height: 0.04, required: true },
    { type: "SIGNATURE", role: "PARTY_B", page: 1, x: 0.32, y: 0.91, width: 0.22, height: 0.05, required: true },
    { type: "DATE_SIGNED", role: "PARTY_B", page: 1, x: 0.56, y: 0.91, width: 0.16, height: 0.04, required: true },
  ]);
}

// ── template definitions ──────────────────────────────────────────────────────

const TEMPLATES: Array<{
  id: string;
  title: string;
  description: string;
  category: string;
  industry: string;
  type: "SECURE_LINK" | "FORM" | "DOCUMENT";
  linkType?: string;
  optionsJson?: string;
  fields?: FieldDef[];
  docSchemaJson?: string;
  docDefaultValuesJson?: string;
  docSigningDefaultsJson?: string;
  docVersion?: number;
  docStatus?: "DRAFT" | "REVIEWED" | "PUBLISHED" | "ARCHIVED";
  thumbnailUrl?: string;
  previewBlobUrl?: string;
  tags: string;
  isFeatured: boolean;
  complianceGuarded: boolean;
  coreFieldLabels?: string[]; // labels of fields that are "locked" in guarded mode
}> = [
  // ── Original 10 (insurance / banking) ─────────────────────────────────────

  {
    id: "tpl-bank-account-collection",
    title: "Bank Account Collection",
    description: "Securely collect routing number, account number, and account type from a client.",
    category: "Banking",
    industry: "BANKING",
    type: "SECURE_LINK",
    linkType: "BANKING_INFO",
    optionsJson: JSON.stringify({ collectBothAccounts: false }),
    tags: "banking,routing,account",
    isFeatured: true,
    complianceGuarded: false,
  },
  {
    id: "tpl-ssn-tax-id-collection",
    title: "SSN / Tax ID Collection",
    description: "Collect a Social Security Number or Tax ID for applications and verifications.",
    category: "Compliance",
    industry: "GENERAL",
    type: "SECURE_LINK",
    linkType: "SSN_ONLY",
    tags: "ssn,tax,compliance,identity",
    isFeatured: false,
    complianceGuarded: false,
  },
  {
    id: "tpl-photo-id-verification",
    title: "Photo ID Verification",
    description: "Ask your client to upload a government-issued photo ID (driver's license or passport).",
    category: "Compliance",
    industry: "GENERAL",
    type: "SECURE_LINK",
    linkType: "ID_UPLOAD",
    optionsJson: JSON.stringify({ documentType: "DRIVERS_LICENSE" }),
    tags: "id,identity,kyc,compliance",
    isFeatured: true,
    complianceGuarded: false,
  },
  {
    id: "tpl-full-client-intake",
    title: "Full Client Intake",
    description: "Collect personal info, SSN, and banking details in a single secure link.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "SECURE_LINK",
    linkType: "FULL_INTAKE",
    tags: "intake,full,insurance,banking",
    isFeatured: true,
    complianceGuarded: false,
  },
  {
    id: "tpl-auto-insurance-quote",
    title: "Auto Insurance Quote",
    description: "Collect driver info, vehicle details, and contact info for an auto insurance quote.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    tags: "auto,vehicle,insurance,quote",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home Address", "address", { required: true }),
      f("Vehicle Year", "text", { placeholder: "e.g. 2021", required: true }),
      f("Vehicle Make & Model", "text", { placeholder: "e.g. Toyota Camry", required: true }),
      f("VIN Number", "text", { required: false, encrypted: true }),
      f("Current Insurance Provider", "text", { required: false }),
      f("Social Security Number", "ssn", { required: false, encrypted: true, maskInput: true, helpText: "Required for MVR check" }),
    ],
  },
  {
    id: "tpl-life-insurance-application",
    title: "Life Insurance Application",
    description: "Collect personal, health, and beneficiary information for a life insurance application.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    tags: "life,insurance,application,beneficiary",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Full Legal Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home Address", "address", { required: true }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Coverage Amount Requested", "dropdown", { required: true, dropdownOptions: dd(["$250,000","$500,000","$750,000","$1,000,000","$2,000,000+"]) }),
      f("Tobacco Use in Last 12 Months?", "dropdown", { required: true, dropdownOptions: dd(["No","Yes"]) }),
      f("Primary Beneficiary Name", "text", { required: true }),
      f("Beneficiary Relationship", "dropdown", { required: true, dropdownOptions: dd(["Spouse","Child","Parent","Sibling","Other"]) }),
    ],
  },
  {
    id: "tpl-health-insurance-enrollment",
    title: "Health Insurance Enrollment",
    description: "Gather personal details and coverage preferences for health insurance enrollment.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    tags: "health,insurance,enrollment,aca",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home Address", "address", { required: true }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Employer Name", "text", { required: false }),
      f("Household Size", "dropdown", { required: true, dropdownOptions: dd(["1","2","3","4","5","6+"]) }),
      f("Annual Household Income", "text", { placeholder: "e.g. $55,000", required: true, encrypted: true }),
      f("Preferred Coverage Type", "dropdown", { required: false, dropdownOptions: dd(["HMO","PPO","EPO","HDHP – HSA Compatible","No Preference"]) }),
    ],
  },
  {
    id: "tpl-mortgage-pre-qualification",
    title: "Mortgage Pre-Qualification",
    description: "Collect income, assets, and banking info needed to pre-qualify a mortgage applicant.",
    category: "Mortgage",
    industry: "MORTGAGE",
    type: "FORM",
    tags: "mortgage,loan,prequalification,banking",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Legal Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Current Address", "address", { required: true }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Gross Annual Income", "text", { placeholder: "e.g. $90,000", required: true, encrypted: true }),
      f("Employment Status", "dropdown", { required: true, dropdownOptions: dd(["Employed Full-Time","Employed Part-Time","Self-Employed","Retired","Other"]) }),
      f("Bank Routing Number", "routing", { required: true, encrypted: true, maskInput: true }),
      f("Bank Account Number", "bank_account", { required: true, encrypted: true, maskInput: true, confirmField: true }),
    ],
  },
  {
    id: "tpl-medicare-supplement-enrollment",
    title: "Medicare Supplement Enrollment",
    description: "Collect Medicare details, personal info, and current coverage for supplement enrollment.",
    category: "Insurance",
    industry: "INSURANCE",
    type: "FORM",
    tags: "medicare,supplement,enrollment,senior",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Full Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home Address", "address", { required: true }),
      f("Medicare Beneficiary Identifier (MBI)", "text", { required: true, encrypted: true, maskInput: true, helpText: "Found on your red, white, and blue Medicare card" }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Part A Effective Date", "date", { required: false }),
      f("Part B Effective Date", "date", { required: false }),
      f("Desired Supplement Plan", "dropdown", { required: false, dropdownOptions: dd(["Plan G","Plan N","Plan F","Plan K","Plan L","Not Sure"]) }),
    ],
  },
  {
    id: "tpl-business-banking-setup",
    title: "Business Banking Setup",
    description: "Collect business entity info, EIN, and banking details for a new business account.",
    category: "Banking",
    industry: "BANKING",
    type: "FORM",
    tags: "business,banking,ein,account",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Business Legal Name", "text", { required: true }),
      f("DBA / Trade Name", "text", { required: false }),
      f("Employer Identification Number (EIN)", "text", { required: true, encrypted: true, maskInput: true }),
      f("Business Type", "dropdown", { required: true, dropdownOptions: dd(["Sole Proprietorship","LLC","S-Corp","C-Corp","Partnership","Non-Profit"]) }),
      f("Business Address", "address", { required: true }),
      f("Owner Full Name", "text", { required: true }),
      f("Owner Date of Birth", "date", { required: true }),
      f("Owner Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Bank Routing Number", "routing", { required: true, encrypted: true, maskInput: true }),
      f("Bank Account Number", "bank_account", { required: true, encrypted: true, maskInput: true, confirmField: true }),
    ],
  },

  // ── HR & Compliance (new 10) ───────────────────────────────────────────────

  {
    id: "tpl-w9-contractor-tax-intake",
    title: "W-9 Contractor Tax Intake",
    description: "IRS-aligned intake to collect taxpayer name, classification, address, TIN, and certification. Use as a precursor to issuing a 1099.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "w9,contractor,tax,irs,tin,1099",
    isFeatured: true,
    complianceGuarded: true,
    coreFieldLabels: ["Legal Name", "Federal Tax Classification", "Address", "TIN Type", "Taxpayer ID Number", "FATCA / Backup Withholding Certification", "Signature", "Date"],
    fields: [
      f("Legal Name", "text", { required: true, helpText: "Name as shown on your income tax return" }),
      f("Business / Disregarded Entity Name", "text", { required: false, helpText: "If different from above — leave blank if same" }),
      f("Federal Tax Classification", "dropdown", { required: true, dropdownOptions: dd(["Individual / Sole Proprietor","C Corporation","S Corporation","Partnership","Trust / Estate","LLC – Single Member (Disregarded)","LLC – C Corp Election","LLC – S Corp Election","LLC – Partnership Election","Other"]) }),
      f("Exempt Payee Code (if any)", "text", { required: false, helpText: "Leave blank if not applicable" }),
      f("FATCA Exemption Code (if any)", "text", { required: false, helpText: "Leave blank if not applicable" }),
      f("Address", "address", { required: true }),
      f("TIN Type", "dropdown", { required: true, dropdownOptions: dd(["Social Security Number (SSN)","Employer Identification Number (EIN)"]) }),
      f("Taxpayer ID Number", "ssn", { required: true, encrypted: true, maskInput: true, helpText: "SSN or EIN — encrypted and stored securely" }),
      f("FATCA / Backup Withholding Certification", "dropdown", { required: true, dropdownOptions: dd(["I certify that the TIN provided is correct, I am not subject to backup withholding, and I am a U.S. person"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-w4-employee-withholding-intake",
    title: "W-4 Employee Withholding Intake",
    description: "IRS-aligned intake for employee federal withholding elections. Employer transfers into official W-4 on file.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "w4,employee,withholding,irs,payroll,tax",
    isFeatured: true,
    complianceGuarded: true,
    coreFieldLabels: ["Filing Status", "Signature", "Date"],
    fields: [
      f("Full Legal Name", "text", { required: true }),
      f("SSN (last 4 for verification)", "text", { required: false, encrypted: true, maskInput: true, helpText: "Optional — for employer records only" }),
      f("Filing Status", "dropdown", { required: true, dropdownOptions: dd(["Single or Married Filing Separately","Married Filing Jointly (or Qualifying Surviving Spouse)","Head of Household"]) }),
      f("Multiple Jobs or Spouse Also Works?", "dropdown", { required: true, dropdownOptions: dd(["Yes","No"]) }),
      f("Claim Dependents — Total Amount", "text", { required: false, encrypted: true, placeholder: "e.g. $2,000", helpText: "From Step 3 of IRS W-4 worksheet" }),
      f("Other Income Not From Jobs (annual)", "text", { required: false, encrypted: true, placeholder: "e.g. $3,000" }),
      f("Deductions (if itemizing)", "text", { required: false, encrypted: true, placeholder: "e.g. $14,000" }),
      f("Additional Withholding Per Pay Period", "text", { required: false, encrypted: true, placeholder: "e.g. $50" }),
      f("Exempt From Withholding?", "dropdown", { required: true, dropdownOptions: dd(["No — withhold per elections above","Yes — I meet both IRS exemption conditions"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-i9-section1-work-authorization",
    title: "I-9 Section 1 — Work Authorization Intake",
    description: "USCIS-aligned Section 1 intake. Employee self-attests identity and work authorization. Note: employer must still complete Section 2 with document verification.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "i9,uscis,i-9,immigration,work,authorization,employment,eligibility",
    isFeatured: true,
    complianceGuarded: true,
    coreFieldLabels: ["Last Name", "First Name", "Date of Birth", "Citizenship / Immigration Status", "Employee Attestation", "Signature", "Date"],
    fields: [
      f("Last Name (Family Name)", "text", { required: true }),
      f("First Name (Given Name)", "text", { required: true }),
      f("Middle Initial", "text", { required: false }),
      f("Other Last Names Used (maiden, etc.)", "text", { required: false }),
      f("Current Address", "address", { required: true }),
      f("Date of Birth", "date", { required: true, encrypted: true }),
      f("U.S. Social Security Number", "ssn", { required: false, encrypted: true, maskInput: true, helpText: "Required only if your employer participates in E-Verify" }),
      f("Email Address", "email", { required: false }),
      f("Phone Number", "phone", { required: false }),
      f("Citizenship / Immigration Status", "dropdown", { required: true, dropdownOptions: dd(["A citizen of the United States","A noncitizen national of the United States","A lawful permanent resident","An alien authorized to work until the date below"]) }),
      f("Alien Registration / USCIS Number (if applicable)", "text", { required: false, encrypted: true, helpText: "A-Number or USCIS Number — starts with A" }),
      f("Form I-94 Admission Number (if applicable)", "text", { required: false, encrypted: true }),
      f("Foreign Passport Number (if applicable)", "text", { required: false, encrypted: true }),
      f("Country of Issuance (if applicable)", "text", { required: false }),
      f("Work Authorization Expiration Date (if applicable)", "date", { required: false }),
      f("Document List Note", "text", { required: false, helpText: "List A (e.g. Passport) OR List B + List C (e.g. Driver License + SSN Card). Your employer will complete Section 2 after reviewing originals." }),
      f("Employee Attestation", "dropdown", { required: true, dropdownOptions: dd(["I attest, under penalty of perjury, that I am aware that federal law provides for imprisonment and/or fines for false statements or use of false documents in connection with the completion of this form"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-direct-deposit-authorization",
    title: "Direct Deposit Authorization",
    description: "Collect employee or contractor banking info to set up direct deposit with a signed authorization.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "direct deposit,payroll,banking,ach,routing,employee",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Employee / Contractor Name", "text", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Bank Name", "text", { required: true }),
      f("Bank Routing Number", "routing", { required: true, encrypted: true, maskInput: true }),
      f("Bank Account Number", "bank_account", { required: true, encrypted: true, maskInput: true, confirmField: true }),
      f("Account Type", "dropdown", { required: true, dropdownOptions: dd(["Checking","Savings"]) }),
      f("Deposit Amount", "dropdown", { required: true, dropdownOptions: dd(["100% of net pay","Partial amount (specify in notes)","Split between accounts (specify in notes)"]) }),
      f("Notes / Special Instructions", "text", { required: false }),
      f("Authorization", "dropdown", { required: true, dropdownOptions: dd(["I authorize the above-named company to initiate credit entries to my account and to reverse any erroneous entries"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-independent-contractor-onboarding",
    title: "Independent Contractor Onboarding",
    description: "Full onboarding intake for new contractors — identity, contact, service type, tax profile, and payment method.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "contractor,onboarding,1099,freelance,independent",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Legal Name", "text", { required: true }),
      f("Business / DBA Name", "text", { required: false }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Business Address", "address", { required: true }),
      f("Service / Work Description", "text", { required: true, placeholder: "e.g. Software development, bookkeeping, design" }),
      f("Federal Tax Classification", "dropdown", { required: true, dropdownOptions: dd(["Sole Proprietor / Individual","Single-Member LLC","Partnership / Multi-Member LLC","S Corporation","C Corporation"]) }),
      f("SSN or EIN", "ssn", { required: true, encrypted: true, maskInput: true, helpText: "Used for 1099 reporting" }),
      f("Payment Method Preference", "dropdown", { required: true, dropdownOptions: dd(["Direct Deposit (ACH)","Check","Wire Transfer","Other"]) }),
      f("Anticipated Start Date", "date", { required: false }),
      f("Acknowledgment", "dropdown", { required: true, dropdownOptions: dd(["I confirm that all information provided is accurate and I understand I am engaged as an independent contractor, not an employee"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-employee-emergency-contact",
    title: "Employee Emergency Contact & Medical Notes",
    description: "Collect primary and secondary emergency contacts, relationship, and optional medical/allergy notes with signed consent.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "emergency contact,employee,medical,allergy,hr",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Employee Full Name", "text", { required: true }),
      f("Employee Email", "email", { required: false }),
      f("Primary Emergency Contact Name", "text", { required: true }),
      f("Primary Contact Relationship", "dropdown", { required: true, dropdownOptions: dd(["Spouse / Partner","Parent","Sibling","Child","Friend","Other"]) }),
      f("Primary Contact Phone", "phone", { required: true }),
      f("Primary Contact Email", "email", { required: false }),
      f("Secondary Emergency Contact Name", "text", { required: false }),
      f("Secondary Contact Relationship", "dropdown", { required: false, dropdownOptions: dd(["Spouse / Partner","Parent","Sibling","Child","Friend","Other"]) }),
      f("Secondary Contact Phone", "phone", { required: false }),
      f("Secondary Contact Email", "email", { required: false }),
      f("Known Medical Conditions / Allergies", "text", { required: false, encrypted: true, helpText: "e.g. Penicillin allergy, diabetes, EpiPen required" }),
      f("Current Medications", "text", { required: false, encrypted: true }),
      f("Special Instructions for Emergency Responders", "text", { required: false, encrypted: true }),
      f("Consent", "dropdown", { required: true, dropdownOptions: dd(["I consent to this information being securely stored and shared with emergency responders if necessary"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-background-check-consent-fcra",
    title: "Background Check Consent (FCRA)",
    description: "FCRA-compliant disclosure and authorization for consumer background reports. Includes standalone disclosure, written authorization, and rights acknowledgment.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "background check,fcra,consent,authorization,screening,hr",
    isFeatured: false,
    complianceGuarded: true,
    coreFieldLabels: ["Applicant Full Name", "Date of Birth", "Social Security Number", "FCRA Disclosure Acknowledgment", "Written Authorization", "Applicant Rights Acknowledgment", "Signature", "Date"],
    fields: [
      f("Applicant Full Name", "text", { required: true }),
      f("Date of Birth", "date", { required: true, encrypted: true }),
      f("Social Security Number", "ssn", { required: true, encrypted: true, maskInput: true }),
      f("Current Address", "address", { required: true }),
      f("Previous Address (if less than 2 years at current)", "text", { required: false }),
      f("Driver's License Number and State (if applicable)", "text", { required: false, encrypted: true }),
      f("FCRA Disclosure Acknowledgment", "dropdown", { required: true, dropdownOptions: dd(["I have received, read, and understand the standalone written disclosure that a consumer report may be obtained for employment purposes"]) }),
      f("Written Authorization", "dropdown", { required: true, dropdownOptions: dd(["I authorize the company and its designated consumer reporting agency to obtain a consumer report and/or investigative consumer report about me"]) }),
      f("Applicant Rights Acknowledgment", "dropdown", { required: true, dropdownOptions: dd(["I acknowledge receipt of 'A Summary of Your Rights Under the Fair Credit Reporting Act'"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-nda-acknowledgment-esign",
    title: "NDA Acknowledgment & E-Sign",
    description: "Capture party details, effective date, and a binding e-signature acknowledging receipt and agreement to the terms of a non-disclosure agreement.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "nda,non-disclosure,confidentiality,agreement,esign",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Legal Name", "text", { required: true }),
      f("Title / Role", "text", { required: false }),
      f("Company / Organization", "text", { required: false }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: false }),
      f("Effective Date of Agreement", "date", { required: true }),
      f("NDA Summary Acknowledgment", "dropdown", { required: true, dropdownOptions: dd(["I have read and understand the Non-Disclosure Agreement presented to me"]) }),
      f("Agreement to Terms", "dropdown", { required: true, dropdownOptions: dd(["I agree to be legally bound by the terms of this Non-Disclosure Agreement"]) }),
      f("Confidential Information Description (optional)", "text", { required: false, helpText: "Briefly describe the nature of information covered, if applicable" }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-offer-letter-acceptance",
    title: "Offer Letter Acceptance",
    description: "Candidate confirms position, start date, and compensation details, then accepts or declines with a binding e-signature.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "FORM",
    tags: "offer letter,hiring,acceptance,onboarding,hr,candidate",
    isFeatured: false,
    complianceGuarded: false,
    fields: [
      f("Candidate Full Name", "text", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: false }),
      f("Position / Job Title", "text", { required: true }),
      f("Department / Team", "text", { required: false }),
      f("Proposed Start Date", "date", { required: true }),
      f("Employment Type", "dropdown", { required: true, dropdownOptions: dd(["Full-Time","Part-Time","Contract","Temporary","Internship"]) }),
      f("Compensation Summary", "text", { required: false, encrypted: true, placeholder: "e.g. $85,000/yr base + benefits", helpText: "Encrypted — only you can view" }),
      f("Decision", "dropdown", { required: true, dropdownOptions: dd(["I accept this offer and agree to the terms outlined","I decline this offer"]) }),
      f("Questions or Comments", "text", { required: false }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  {
    id: "tpl-general-new-client-secure-intake",
    title: "General New Client Secure Intake",
    description: "Flexible all-purpose intake — identity, contact, address, optional SSN/TIN, optional banking, file upload notes, and signed consent.",
    category: "General",
    industry: "GENERAL",
    type: "FORM",
    tags: "intake,general,client,onboarding,identity",
    isFeatured: true,
    complianceGuarded: false,
    fields: [
      f("Full Name", "text", { required: true }),
      f("Email Address", "email", { required: true }),
      f("Phone Number", "phone", { required: true }),
      f("Home / Business Address", "address", { required: true }),
      f("Date of Birth", "date", { required: false, encrypted: true }),
      f("Social Security Number or TIN", "ssn", { required: false, encrypted: true, maskInput: true, helpText: "Optional — only provide if requested by your agent" }),
      f("Bank Routing Number", "routing", { required: false, encrypted: true, maskInput: true }),
      f("Bank Account Number", "bank_account", { required: false, encrypted: true, maskInput: true, confirmField: true }),
      f("Document Upload Notes", "text", { required: false, helpText: "List any documents you intend to provide separately (e.g. photo ID, proof of income)" }),
      f("Consent", "dropdown", { required: true, dropdownOptions: dd(["I authorize submission of the above information and confirm it is accurate to the best of my knowledge"]) }),
      f("Signature", "signature", { required: true }),
      f("Date", "date", { required: true }),
    ],
  },
  // ── Document Templates (new) ───────────────────────────────────────────────
  {
    id: "tpl-doc-nda-v1",
    title: "Non-Disclosure Agreement",
    description: "Mutual NDA template with signature-ready sections.",
    category: "Compliance",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "nda,confidentiality,document,signature",
    isFeatured: true,
    complianceGuarded: false,
    docSchemaJson: docSchema("Non-Disclosure Agreement", [
      "Each party agrees to keep confidential information private and to use it only for the permitted business purpose.",
      "Confidential information includes all non-public business, financial, technical, and customer information shared by either party.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-offer-letter-v1",
    title: "Offer Letter",
    description: "Employment offer letter template with acceptance signature block.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "offer letter,employment,document,signature",
    isFeatured: true,
    complianceGuarded: false,
    docSchemaJson: docSchema("Offer Letter", [
      "This letter confirms the position title, compensation terms, start date, and reporting structure offered by the company.",
      "The candidate acknowledges that employment remains subject to applicable company policies and legal requirements.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-invoice-v1",
    title: "Invoice",
    description: "Invoice document template with customer acceptance signature.",
    category: "Banking",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "invoice,billing,accounts receivable,document",
    isFeatured: false,
    complianceGuarded: false,
    docSchemaJson: docSchema("Invoice", [
      "This invoice reflects services rendered and amounts due under the agreed scope of work.",
      "Payment is due according to the terms listed in this invoice and any supporting agreement.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-purchase-order-v1",
    title: "Purchase Order",
    description: "Purchase order template for ordering goods/services.",
    category: "Banking",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "purchase order,procurement,document",
    isFeatured: false,
    complianceGuarded: false,
    docSchemaJson: docSchema("Purchase Order", [
      "This purchase order authorizes the supplier to provide specified goods or services under the listed terms.",
      "Supplier acceptance confirms agreement to pricing, delivery timelines, and applicable quality standards.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-bill-of-sale-v1",
    title: "Bill of Sale",
    description: "General bill of sale template for transfer of property.",
    category: "General",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "bill of sale,asset transfer,document",
    isFeatured: true,
    complianceGuarded: false,
    docSchemaJson: docSchema("Bill of Sale", [
      "The seller hereby transfers ownership of the described property to the buyer for agreed consideration.",
      "The property is conveyed according to the warranties and conditions stated in this agreement.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-lease-agreement-v1",
    title: "Lease Agreement",
    description: "Lease agreement template for landlord and tenant execution.",
    category: "General",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "lease,rental,property,document",
    isFeatured: false,
    complianceGuarded: false,
    docSchemaJson: docSchema("Lease Agreement", [
      "This lease sets out the rental term, payment obligations, and use-of-premises conditions between landlord and tenant.",
      "The parties agree to comply with all maintenance, notice, and legal responsibilities defined herein.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-loan-agreement-v1",
    title: "Loan Agreement",
    description: "Loan agreement template for lender and borrower.",
    category: "Banking",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "loan,lender,borrower,document",
    isFeatured: false,
    complianceGuarded: false,
    docSchemaJson: docSchema("Loan Agreement", [
      "The lender agrees to extend funds to the borrower under the principal, interest, and repayment terms in this agreement.",
      "Borrower obligations, default conditions, and remedies are governed by the terms listed herein.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-liability-waiver-v1",
    title: "Liability Waiver",
    description: "Liability waiver and acknowledgment of risk template.",
    category: "Compliance",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "liability,waiver,risk,document",
    isFeatured: true,
    complianceGuarded: false,
    docSchemaJson: docSchema("Liability Waiver", [
      "The participant acknowledges and accepts risks associated with the activity and voluntarily elects to proceed.",
      "The participant releases and holds harmless the organization to the extent permitted by law.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-service-agreement-v1",
    title: "Service Agreement",
    description: "Service agreement template for provider and client engagements.",
    category: "General",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "service agreement,scope,document",
    isFeatured: true,
    complianceGuarded: false,
    docSchemaJson: docSchema("Service Agreement", [
      "This agreement defines the scope of services, performance standards, deliverables, and payment terms.",
      "Both parties agree to the timeline, communication process, and responsibilities outlined herein.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
  {
    id: "tpl-doc-independent-contractor-agreement-v1",
    title: "Independent Contractor Agreement",
    description: "Independent contractor agreement template with signature sections.",
    category: "HR & Compliance",
    industry: "GENERAL",
    type: "DOCUMENT",
    tags: "independent contractor,1099,agreement,document",
    isFeatured: false,
    complianceGuarded: false,
    docSchemaJson: docSchema("Independent Contractor Agreement", [
      "Contractor will provide services as an independent business and not as an employee of the company.",
      "Compensation, confidentiality, ownership, and termination terms are governed by this agreement.",
    ]),
    docDefaultValuesJson: JSON.stringify({ effective_date: "March 29, 2026" }),
    docSigningDefaultsJson: docSigningDefaults(),
    docVersion: 1,
    docStatus: "PUBLISHED",
  },
];

// ── seed ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Seeding system templates...");

  for (const t of TEMPLATES) {
    const fieldsJson = t.fields ? JSON.stringify(t.fields) : null;
    const coreFieldLabels = t.coreFieldLabels ? JSON.stringify(t.coreFieldLabels) : null;

    await prisma.systemTemplate.upsert({
      where: { id: t.id },
      update: {
        title: t.title,
        description: t.description,
        category: t.category,
        industry: t.industry,
        type: t.type,
        linkType: t.linkType ?? null,
        optionsJson: t.optionsJson ?? null,
        fieldsJson,
        docSchemaJson: t.docSchemaJson ?? null,
        docDefaultValuesJson: t.docDefaultValuesJson ?? null,
        docSigningDefaultsJson: t.docSigningDefaultsJson ?? null,
        docVersion: t.docVersion ?? 1,
        docStatus: t.docStatus ?? "DRAFT",
        thumbnailUrl: t.thumbnailUrl ?? null,
        previewBlobUrl: t.previewBlobUrl ?? null,
        tags: t.tags,
        isFeatured: t.isFeatured,
        complianceGuarded: t.complianceGuarded,
        coreFieldLabels,
        isActive: true,
      },
      create: {
        id: t.id,
        title: t.title,
        description: t.description,
        category: t.category,
        industry: t.industry,
        type: t.type,
        linkType: t.linkType ?? null,
        optionsJson: t.optionsJson ?? null,
        fieldsJson,
        docSchemaJson: t.docSchemaJson ?? null,
        docDefaultValuesJson: t.docDefaultValuesJson ?? null,
        docSigningDefaultsJson: t.docSigningDefaultsJson ?? null,
        docVersion: t.docVersion ?? 1,
        docStatus: t.docStatus ?? "DRAFT",
        thumbnailUrl: t.thumbnailUrl ?? null,
        previewBlobUrl: t.previewBlobUrl ?? null,
        tags: t.tags,
        isFeatured: t.isFeatured,
        complianceGuarded: t.complianceGuarded,
        coreFieldLabels,
        isActive: true,
      },
    });
    console.log(`  ✓ ${t.title}`);
  }

  console.log(`\nSeeded ${TEMPLATES.length} system templates.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
